#!/usr/bin/env python3
"""Generate the profile README and numbered post index pages."""

from __future__ import annotations

import re
import subprocess
import sys
import tomllib
from dataclasses import dataclass
from datetime import date, datetime
from pathlib import Path
from typing import Any
from zoneinfo import ZoneInfo, ZoneInfoNotFoundError


ROOT = Path(__file__).resolve().parents[1]
CONFIG_PATH = ROOT / "config.toml"
GENERATED_NOTICE = "<!-- Generated by tools/build.py. Do not edit directly. -->"
PAGE_PATTERN = re.compile(r"page([2-9][0-9]*)\.md")


class BuildError(Exception):
    """A user-facing build error."""


@dataclass(frozen=True)
class Entry:
    slug: str
    title: str
    path: Path | None
    url: str | None
    created: date
    updated: date
    summary: str = ""
    tags: tuple[str, ...] = ()


def load_config() -> dict[str, Any]:
    try:
        with CONFIG_PATH.open("rb") as file:
            return tomllib.load(file)
    except FileNotFoundError as error:
        raise BuildError(f"missing configuration: {CONFIG_PATH}") from error
    except tomllib.TOMLDecodeError as error:
        raise BuildError(f"invalid TOML in {CONFIG_PATH}: {error}") from error


def run_git(*arguments: str) -> str:
    command = ["git", "-C", str(ROOT), *arguments]
    try:
        result = subprocess.run(
            command,
            check=True,
            capture_output=True,
            text=True,
        )
    except FileNotFoundError as error:
        raise BuildError("git is required to derive article dates") from error
    except subprocess.CalledProcessError as error:
        message = error.stderr.strip() or "unknown Git error"
        raise BuildError(f"git command failed: {message}") from error
    return result.stdout


def is_dirty(path: Path) -> bool:
    relative = path.relative_to(ROOT).as_posix()
    return bool(run_git("status", "--porcelain", "--", relative).strip())


def git_dates(path: Path, today: date) -> tuple[date, date]:
    """Return creation and update dates, with working-tree-aware fallbacks."""
    relative = path.relative_to(ROOT).as_posix()
    output = run_git("log", "--follow", "--format=%aI", "--", relative)
    timestamps = [
        datetime.fromisoformat(line.strip()).date()
        for line in output.splitlines()
        if line.strip()
    ]

    if not timestamps:
        return today, today

    created = timestamps[-1]
    updated = today if is_dirty(path) else timestamps[0]
    return created, updated


def parse_scalar(value: str) -> str:
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {'"', "'"}:
        return value[1:-1]
    return value


def parse_tags(value: str, path: Path) -> tuple[str, ...]:
    value = value.strip()
    if not value.startswith("[") or not value.endswith("]"):
        raise BuildError(f"{path}: tags must be a one-line list such as [cpp, linux]")
    items = [parse_scalar(item) for item in value[1:-1].split(",")]
    return tuple(item for item in items if item)


def parse_published_at(value: str, path: Path) -> date:
    value = parse_scalar(value)
    try:
        published_at = date.fromisoformat(value)
    except ValueError as error:
        raise BuildError(f"{path}: published_at must use YYYY-MM-DD") from error
    if published_at.isoformat() != value:
        raise BuildError(f"{path}: published_at must use YYYY-MM-DD")
    return published_at


def parse_markdown(path: Path) -> tuple[str, tuple[str, ...], date | None]:
    text = path.read_text(encoding="utf-8")
    title: str | None = None
    tags: tuple[str, ...] = ()
    published_at: date | None = None
    body = text

    if text.startswith("---\n"):
        end = text.find("\n---\n", 4)
        if end == -1:
            raise BuildError(f"{path}: front matter is missing its closing ---")
        metadata = text[4:end]
        body = text[end + 5 :]
        for line_number, line in enumerate(metadata.splitlines(), start=2):
            if not line.strip() or line.lstrip().startswith("#"):
                continue
            key, separator, value = line.partition(":")
            if not separator:
                raise BuildError(f"{path}:{line_number}: expected key: value")
            key = key.strip()
            if key == "title":
                title = parse_scalar(value)
            elif key == "tags":
                tags = parse_tags(value, path)
            elif key == "published_at":
                published_at = parse_published_at(value, path)
            else:
                raise BuildError(f"{path}:{line_number}: unsupported metadata key {key!r}")

    if not title:
        heading = re.search(r"^#\s+(.+?)\s*$", body, re.MULTILINE)
        if heading:
            title = heading.group(1)
    if not title:
        raise BuildError(f"{path}: add a title in front matter or a level-one heading")

    return title, tags, published_at


def scan_directory(directory_name: str, today: date) -> list[Entry]:
    directory = ROOT / directory_name
    if not directory.exists():
        return []

    entries: list[Entry] = []
    for path in sorted(directory.glob("*.md")):
        if path.name.casefold() == "readme.md":
            continue
        title, tags, published_at = parse_markdown(path)
        git_created, updated = git_dates(path, today)
        if published_at and published_at > today:
            raise BuildError(f"{path}: published_at cannot be in the future")
        created = published_at or git_created
        entries.append(
            Entry(
                slug=path.stem,
                title=title,
                path=path.relative_to(ROOT),
                url=None,
                created=created,
                updated=updated,
                tags=tags,
            )
        )
    return sorted(entries, key=lambda entry: (entry.created, entry.slug), reverse=True)


def external_posts(config: dict[str, Any]) -> list[Entry]:
    entries: list[Entry] = []
    for item in config.get("external_posts", []):
        try:
            entry_date = item["date"]
            if not isinstance(entry_date, date):
                raise TypeError("date must be a TOML date")
            entries.append(
                Entry(
                    slug=item["slug"],
                    title=item["title"],
                    path=None,
                    url=item["url"],
                    created=entry_date,
                    updated=entry_date,
                    summary=item.get("summary", ""),
                )
            )
        except (KeyError, TypeError) as error:
            raise BuildError(f"invalid external_posts entry: {error}") from error
    return entries


def relative_link(entry: Entry, from_toc: bool = False) -> str:
    if entry.url:
        return entry.url
    if entry.path is None:
        raise BuildError(f"entry {entry.slug!r} has neither path nor URL")
    prefix = "../" if from_toc else ""
    return prefix + entry.path.as_posix()


def entry_line(entry: Entry, from_toc: bool = False) -> str:
    line = f"- `{entry.created.isoformat()}` [{entry.title}]({relative_link(entry, from_toc)})"
    if entry.summary:
        line += f" — {entry.summary}"
    return line


def render_home(
    config: dict[str, Any],
    posts: list[Entry],
    tils: list[Entry],
    featured: list[Entry],
) -> str:
    name = config["name"]
    intro = " ".join(config["intro"].split())
    lines = [
        GENERATED_NOTICE,
        "",
        f"# {name}",
        "",
        intro,
        "",
        f"[Posts](#recent-posts) · [TIL](#recent-tils) · [GitHub]({config['github']})",
        "",
        "## Featured",
        "",
    ]
    lines.extend(entry_line(entry) for entry in featured)

    lines.extend(["", "## Recent Posts", ""])
    page_size = config["posts_per_page"]
    if posts:
        lines.extend(entry_line(entry) for entry in posts[:page_size])
    else:
        lines.append("New posts will appear here.")
    if len(posts) > page_size:
        lines.extend(["", "[Older posts →](toc/page2.md)"])

    lines.extend(["", "## Recent TILs", ""])
    if tils:
        lines.extend(entry_line(entry) for entry in tils[: config["recent_tils"]])
    else:
        lines.append("Short notes will appear here.")

    lines.extend(["", "## Projects", ""])
    for project in config.get("projects", []):
        lines.append(
            f"- [{project['name']}]({project['url']}) — {project['description']}"
        )

    lines.extend(
        [
            "",
            "## Contact",
            "",
            f"[Email](mailto:{config['email']}) · [LinkedIn]({config['linkedin']})",
            "",
        ]
    )
    return "\n".join(lines)


def render_page(entries: list[Entry], page_number: int, total_pages: int) -> str:
    newer = "../README.md" if page_number == 2 else f"page{page_number - 1}.md"
    navigation = [f"[← Newer]({newer})", "[Home](../README.md)"]
    if page_number < total_pages:
        navigation.append(f"[Older →](page{page_number + 1}.md)")

    lines = [
        GENERATED_NOTICE,
        "",
        f"# Posts — Page {page_number}",
        "",
        " · ".join(navigation),
        "",
    ]
    lines.extend(entry_line(entry, from_toc=True) for entry in entries)
    lines.extend(["", " · ".join(navigation), ""])
    return "\n".join(lines)


def write_if_changed(path: Path, content: str) -> None:
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")


def generate_pages(posts: list[Entry], page_size: int) -> None:
    toc = ROOT / "toc"
    pages = [posts[index : index + page_size] for index in range(0, len(posts), page_size)]
    expected: set[Path] = set()

    for page_number, entries in enumerate(pages[1:], start=2):
        path = toc / f"page{page_number}.md"
        expected.add(path)
        write_if_changed(path, render_page(entries, page_number, len(pages)))

    if toc.exists():
        for path in toc.iterdir():
            if path.is_file() and PAGE_PATTERN.fullmatch(path.name) and path not in expected:
                path.unlink()
        if not any(toc.iterdir()):
            toc.rmdir()


def validate_config(config: dict[str, Any]) -> None:
    for key in ("name", "intro", "github", "email", "linkedin", "timezone"):
        if not isinstance(config.get(key), str) or not config[key].strip():
            raise BuildError(f"config key {key!r} must be a non-empty string")
    for key in ("posts_per_page", "recent_tils"):
        if not isinstance(config.get(key), int) or config[key] <= 0:
            raise BuildError(f"config key {key!r} must be a positive integer")
    try:
        ZoneInfo(config["timezone"])
    except ZoneInfoNotFoundError as error:
        raise BuildError(f"unknown timezone {config['timezone']!r}") from error


def main() -> int:
    try:
        config = load_config()
        validate_config(config)
        today = datetime.now(ZoneInfo(config["timezone"])).date()
        internal_posts = scan_directory("posts", today)
        posts = sorted(
            [*internal_posts, *external_posts(config)],
            key=lambda entry: (entry.created, entry.slug),
            reverse=True,
        )
        tils = scan_directory("til", today)

        by_slug = {entry.slug: entry for entry in posts}
        featured: list[Entry] = []
        for slug in config.get("featured_posts", []):
            if slug not in by_slug:
                raise BuildError(f"featured post {slug!r} does not exist")
            featured.append(by_slug[slug])

        write_if_changed(ROOT / "README.md", render_home(config, posts, tils, featured))
        generate_pages(posts, config["posts_per_page"])
    except (BuildError, KeyError, OSError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
