#!/usr/bin/env python3
"""Generate the profile README, post pagination, and per-tag indexes."""

from __future__ import annotations

import re
import subprocess
import sys
import tomllib
from dataclasses import dataclass
from datetime import date, datetime
from pathlib import Path
from typing import Any
from zoneinfo import ZoneInfo, ZoneInfoNotFoundError


ROOT = Path(__file__).resolve().parents[1]
CONFIG_PATH = ROOT / "config.toml"
GENERATED_NOTICE = "<!-- Generated by tools/build.py. Do not edit directly. -->"
PAGE_PATTERN = re.compile(r"page([2-9][0-9]*)\.md")
TAG_PATTERN = re.compile(r"^[A-Za-z0-9_-]+$")
# Hub: toc/tag/<tag>.md (depth 2). Show-all: toc/tag/<tag>/posts|tils/<n>.md (depth 4).
TAG_HUB_DEPTH = 2
TAG_LIST_DEPTH = 4


class BuildError(Exception):
    """A user-facing build error."""


@dataclass(frozen=True)
class Entry:
    slug: str
    title: str
    path: Path | None
    url: str | None
    created: date
    updated: date
    summary: str = ""
    tags: tuple[str, ...] = ()


def load_config() -> dict[str, Any]:
    try:
        with CONFIG_PATH.open("rb") as file:
            return tomllib.load(file)
    except FileNotFoundError as error:
        raise BuildError(f"missing configuration: {CONFIG_PATH}") from error
    except tomllib.TOMLDecodeError as error:
        raise BuildError(f"invalid TOML in {CONFIG_PATH}: {error}") from error


def run_git(*arguments: str) -> str:
    command = ["git", "-C", str(ROOT), *arguments]
    try:
        result = subprocess.run(
            command,
            check=True,
            capture_output=True,
            text=True,
        )
    except FileNotFoundError as error:
        raise BuildError("git is required to derive article dates") from error
    except subprocess.CalledProcessError as error:
        message = error.stderr.strip() or "unknown Git error"
        raise BuildError(f"git command failed: {message}") from error
    return result.stdout


def is_dirty(path: Path) -> bool:
    relative = path.relative_to(ROOT).as_posix()
    return bool(run_git("status", "--porcelain", "--", relative).strip())


def git_dates(path: Path, today: date) -> tuple[date, date]:
    """Return creation and update dates, with working-tree-aware fallbacks."""
    relative = path.relative_to(ROOT).as_posix()
    output = run_git("log", "--follow", "--format=%aI", "--", relative)
    timestamps = [
        datetime.fromisoformat(line.strip()).date()
        for line in output.splitlines()
        if line.strip()
    ]

    if not timestamps:
        return today, today

    created = timestamps[-1]
    updated = today if is_dirty(path) else timestamps[0]
    return created, updated


def parse_scalar(value: str) -> str:
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {'"', "'"}:
        return value[1:-1]
    return value


def parse_tags(value: str, path: Path) -> tuple[str, ...]:
    value = value.strip()
    if not value.startswith("[") or not value.endswith("]"):
        raise BuildError(f"{path}: tags must be a one-line list such as [cpp, linux]")
    tags: list[str] = []
    for item in (parse_scalar(part) for part in value[1:-1].split(",")):
        if not item:
            continue
        if not TAG_PATTERN.fullmatch(item):
            raise BuildError(
                f"{path}: invalid tag {item!r}; tags must match {TAG_PATTERN.pattern}"
            )
        if item not in tags:
            tags.append(item)
    return tuple(tags)


def parse_published_at(value: str, path: Path) -> date:
    value = parse_scalar(value)
    try:
        published_at = date.fromisoformat(value)
    except ValueError as error:
        raise BuildError(f"{path}: published_at must use YYYY-MM-DD") from error
    if published_at.isoformat() != value:
        raise BuildError(f"{path}: published_at must use YYYY-MM-DD")
    return published_at


def parse_markdown(path: Path) -> tuple[str, tuple[str, ...], date | None]:
    text = path.read_text(encoding="utf-8")
    title: str | None = None
    tags: tuple[str, ...] = ()
    published_at: date | None = None
    body = text

    if text.startswith("---\n"):
        end = text.find("\n---\n", 4)
        if end == -1:
            raise BuildError(f"{path}: front matter is missing its closing ---")
        metadata = text[4:end]
        body = text[end + 5 :]
        for line_number, line in enumerate(metadata.splitlines(), start=2):
            if not line.strip() or line.lstrip().startswith("#"):
                continue
            key, separator, value = line.partition(":")
            if not separator:
                raise BuildError(f"{path}:{line_number}: expected key: value")
            key = key.strip()
            if key == "title":
                title = parse_scalar(value)
            elif key == "tags":
                tags = parse_tags(value, path)
            elif key == "published_at":
                published_at = parse_published_at(value, path)
            else:
                raise BuildError(f"{path}:{line_number}: unsupported metadata key {key!r}")

    if not title:
        heading = re.search(r"^#\s+(.+?)\s*$", body, re.MULTILINE)
        if heading:
            title = heading.group(1)
    if not title:
        raise BuildError(f"{path}: add a title in front matter or a level-one heading")

    return title, tags, published_at


def scan_directory(directory_name: str, today: date) -> list[Entry]:
    directory = ROOT / directory_name
    if not directory.exists():
        return []

    entries: list[Entry] = []
    for path in sorted(directory.glob("*.md")):
        if path.name.casefold() == "readme.md":
            continue
        title, tags, published_at = parse_markdown(path)
        git_created, updated = git_dates(path, today)
        if published_at and published_at > today:
            raise BuildError(f"{path}: published_at cannot be in the future")
        created = published_at or git_created
        entries.append(
            Entry(
                slug=path.stem,
                title=title,
                path=path.relative_to(ROOT),
                url=None,
                created=created,
                updated=updated,
                tags=tags,
            )
        )
    return sorted(entries, key=lambda entry: (entry.created, entry.slug), reverse=True)


def external_posts(config: dict[str, Any]) -> list[Entry]:
    entries: list[Entry] = []
    for item in config.get("external_posts", []):
        try:
            entry_date = item["date"]
            if not isinstance(entry_date, date):
                raise TypeError("date must be a TOML date")
            entries.append(
                Entry(
                    slug=item["slug"],
                    title=item["title"],
                    path=None,
                    url=item["url"],
                    created=entry_date,
                    updated=entry_date,
                    summary=item.get("summary", ""),
                )
            )
        except (KeyError, TypeError) as error:
            raise BuildError(f"invalid external_posts entry: {error}") from error
    return entries


def relative_link(entry: Entry, depth: int = 0) -> str:
    """Link to an article from a generated page `depth` directories below ROOT."""
    if entry.url:
        return entry.url
    if entry.path is None:
        raise BuildError(f"entry {entry.slug!r} has neither path nor URL")
    return f"{'../' * depth}{entry.path.as_posix()}"


def entry_line(entry: Entry, depth: int = 0) -> str:
    line = f"- `{entry.created.isoformat()}` [{entry.title}]({relative_link(entry, depth)})"
    if entry.summary:
        line += f" — {entry.summary}"
    return line


def grouped_tags(entries: list[Entry]) -> dict[str, list[Entry]]:
    groups: dict[str, list[Entry]] = {}
    for entry in entries:
        for tag in entry.tags:
            tagged = groups.setdefault(tag, [])
            if not tagged or tagged[-1] is not entry:
                tagged.append(entry)
    return groups


def validate_tag_casefold(entries: list[Entry]) -> None:
    canonical: dict[str, str] = {}
    for entry in entries:
        location = entry.path if entry.path is not None else entry.slug
        for tag in entry.tags:
            key = tag.casefold()
            previous = canonical.get(key)
            if previous is None:
                canonical[key] = tag
            elif previous != tag:
                raise BuildError(
                    f"{location}: tag {tag!r} differs only by case from {previous!r}"
                )


def format_tag_counts(post_count: int, til_count: int) -> str:
    parts: list[str] = []
    if post_count:
        parts.append("1 post" if post_count == 1 else f"{post_count} posts")
    if til_count:
        parts.append("1 TIL" if til_count == 1 else f"{til_count} TILs")
    return ", ".join(parts)


def paginate(entries: list[Entry], page_size: int) -> list[list[Entry]]:
    return [entries[index : index + page_size] for index in range(0, len(entries), page_size)]


def render_home(
    config: dict[str, Any],
    posts: list[Entry],
    tils: list[Entry],
    featured: list[Entry],
) -> str:
    name = config["name"]
    intro = " ".join(config["intro"].split())
    post_tags = grouped_tags(posts)
    til_tags = grouped_tags(tils)
    tags = sorted(set(post_tags) | set(til_tags))
    nav = ["[Posts](#recent-posts)", "[TIL](#recent-tils)"]
    if tags:
        nav.append("[Tags](#tags)")
    nav.append(f"[GitHub]({config['github']})")
    lines = [
        GENERATED_NOTICE,
        "",
        f"# {name}",
        "",
        intro,
        "",
        " · ".join(nav),
        "",
        "## Featured",
        "",
    ]
    lines.extend(entry_line(entry) for entry in featured)

    lines.extend(["", "## Recent Posts", ""])
    page_size = config["posts_per_page"]
    if posts:
        lines.extend(entry_line(entry) for entry in posts[:page_size])
    else:
        lines.append("New posts will appear here.")
    if len(posts) > page_size:
        lines.extend(["", "[Older posts →](toc/page2.md)"])

    lines.extend(["", "## Recent TILs", ""])
    if tils:
        lines.extend(entry_line(entry) for entry in tils[: config["recent_tils"]])
    else:
        lines.append("Short notes will appear here.")

    lines.extend(["", "## Projects", ""])
    for project in config.get("projects", []):
        lines.append(
            f"- [{project['name']}]({project['url']}) — {project['description']}"
        )

    if tags:
        rendered = []
        for tag in tags:
            counts = format_tag_counts(
                len(post_tags.get(tag, [])),
                len(til_tags.get(tag, [])),
            )
            rendered.append(f"[`{tag}`](toc/tag/{tag}.md) ({counts})")
        lines.extend(["", "## Tags", "", " · ".join(rendered)])

    lines.extend(
        [
            "",
            "## Contact",
            "",
            f"[Email](mailto:{config['email']}) · [LinkedIn]({config['linkedin']})",
            "",
        ]
    )
    return "\n".join(lines)


def render_page(entries: list[Entry], page_number: int, total_pages: int) -> str:
    newer = "../README.md" if page_number == 2 else f"page{page_number - 1}.md"
    navigation = [f"[← Newer]({newer})", "[Home](../README.md)"]
    if page_number < total_pages:
        navigation.append(f"[Older →](page{page_number + 1}.md)")

    lines = [
        GENERATED_NOTICE,
        "",
        f"# Posts — Page {page_number}",
        "",
        " · ".join(navigation),
        "",
    ]
    lines.extend(entry_line(entry, depth=1) for entry in entries)
    lines.extend(["", " · ".join(navigation), ""])
    return "\n".join(lines)


def render_tag_hub(tag: str, posts: list[Entry], tils: list[Entry], page_size: int) -> str:
    lines = [GENERATED_NOTICE, "", f"# {tag}", ""]
    if posts:
        lines.extend(["## Posts", ""])
        lines.extend(entry_line(entry, depth=TAG_HUB_DEPTH) for entry in posts[:page_size])
        if len(posts) > page_size:
            lines.extend(["", f"[Show all posts →]({tag}/posts/1.md)"])
        lines.append("")
    if tils:
        lines.extend(["## TILs", ""])
        lines.extend(entry_line(entry, depth=TAG_HUB_DEPTH) for entry in tils[:page_size])
        if len(tils) > page_size:
            lines.extend(["", f"[Show all TILs →]({tag}/tils/1.md)"])
        lines.append("")
    return "\n".join(lines)


def render_tag_list_page(
    tag: str,
    heading: str,
    entries: list[Entry],
    page_number: int,
    total_pages: int,
) -> str:
    navigation: list[str] = []
    if page_number > 1:
        navigation.append(f"[← Newer]({page_number - 1}.md)")
    navigation.append(f"[{tag}](../../{tag}.md)")
    if page_number < total_pages:
        navigation.append(f"[Older →]({page_number + 1}.md)")

    lines = [
        GENERATED_NOTICE,
        "",
        f"# {tag} — {heading} — Page {page_number}",
        "",
        " · ".join(navigation),
        "",
    ]
    lines.extend(entry_line(entry, depth=TAG_LIST_DEPTH) for entry in entries)
    lines.extend(["", " · ".join(navigation), ""])
    return "\n".join(lines)


def write_if_changed(path: Path, content: str) -> None:
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")


def generate_pages(posts: list[Entry], page_size: int) -> None:
    toc = ROOT / "toc"
    pages = paginate(posts, page_size)
    expected: set[Path] = set()

    for page_number, entries in enumerate(pages[1:], start=2):
        path = toc / f"page{page_number}.md"
        expected.add(path)
        write_if_changed(path, render_page(entries, page_number, len(pages)))

    if toc.exists():
        for path in toc.iterdir():
            if path.is_file() and PAGE_PATTERN.fullmatch(path.name) and path not in expected:
                path.unlink()
        if not any(toc.iterdir()):
            toc.rmdir()


def is_obsolete_tag_output(path: Path, tag_root: Path) -> bool:
    parts = path.relative_to(tag_root).parts
    if len(parts) == 1 and path.suffix == ".md":
        return True
    return (
        len(parts) == 3
        and parts[1] in {"posts", "tils"}
        and path.suffix == ".md"
    )


def cleanup_tag_outputs(tag_root: Path, expected: set[Path]) -> None:
    if not tag_root.exists():
        return

    for path in sorted(tag_root.rglob("*"), key=lambda item: len(item.parts), reverse=True):
        if path.is_file():
            if path not in expected and is_obsolete_tag_output(path, tag_root):
                path.unlink()
        elif path.is_dir() and not any(path.iterdir()):
            path.rmdir()

    if tag_root.exists() and not any(tag_root.iterdir()):
        tag_root.rmdir()


def write_tag_list_pages(
    tag_root: Path,
    tag: str,
    subdir: str,
    heading: str,
    entries: list[Entry],
    page_size: int,
) -> set[Path]:
    expected: set[Path] = set()
    pages = paginate(entries, page_size)
    total_pages = len(pages)
    for page_number, page_entries in enumerate(pages, start=1):
        path = tag_root / tag / subdir / f"{page_number}.md"
        expected.add(path)
        write_if_changed(
            path,
            render_tag_list_page(tag, heading, page_entries, page_number, total_pages),
        )
    return expected


def generate_tag_indexes(
    posts: list[Entry],
    tils: list[Entry],
    page_size: int,
) -> None:
    tag_root = ROOT / "toc" / "tag"
    post_tags = grouped_tags(posts)
    til_tags = grouped_tags(tils)
    expected: set[Path] = set()

    for tag in sorted(set(post_tags) | set(til_tags)):
        tagged_posts = post_tags.get(tag, [])
        tagged_tils = til_tags.get(tag, [])
        hub = tag_root / f"{tag}.md"
        expected.add(hub)
        write_if_changed(hub, render_tag_hub(tag, tagged_posts, tagged_tils, page_size))
        if len(tagged_posts) > page_size:
            expected.update(
                write_tag_list_pages(
                    tag_root, tag, "posts", "Posts", tagged_posts, page_size
                )
            )
        if len(tagged_tils) > page_size:
            expected.update(
                write_tag_list_pages(
                    tag_root, tag, "tils", "TILs", tagged_tils, page_size
                )
            )

    cleanup_tag_outputs(tag_root, expected)


def print_tags(posts: list[Entry], tils: list[Entry]) -> None:
    post_tags = grouped_tags(posts)
    til_tags = grouped_tags(tils)
    for tag in sorted(set(post_tags) | set(til_tags)):
        counts = format_tag_counts(
            len(post_tags.get(tag, [])),
            len(til_tags.get(tag, [])),
        )
        print(f"{tag} ({counts})")


def validate_config(config: dict[str, Any]) -> None:
    for key in ("name", "intro", "github", "email", "linkedin", "timezone"):
        if not isinstance(config.get(key), str) or not config[key].strip():
            raise BuildError(f"config key {key!r} must be a non-empty string")
    for key in ("posts_per_page", "recent_tils"):
        if not isinstance(config.get(key), int) or config[key] <= 0:
            raise BuildError(f"config key {key!r} must be a positive integer")
    try:
        ZoneInfo(config["timezone"])
    except ZoneInfoNotFoundError as error:
        raise BuildError(f"unknown timezone {config['timezone']!r}") from error


def main() -> int:
    try:
        argv = sys.argv[1:]
        if argv not in ([], ["tags"]):
            raise BuildError("usage: python tools/build.py [tags]")
        list_only = argv == ["tags"]

        config = load_config()
        validate_config(config)
        today = datetime.now(ZoneInfo(config["timezone"])).date()
        internal_posts = scan_directory("posts", today)
        tils = scan_directory("til", today)
        validate_tag_casefold([*internal_posts, *tils])

        if list_only:
            print_tags(internal_posts, tils)
            return 0

        posts = sorted(
            [*internal_posts, *external_posts(config)],
            key=lambda entry: (entry.created, entry.slug),
            reverse=True,
        )

        by_slug = {entry.slug: entry for entry in posts}
        featured: list[Entry] = []
        for slug in config.get("featured_posts", []):
            if slug not in by_slug:
                raise BuildError(f"featured post {slug!r} does not exist")
            featured.append(by_slug[slug])

        page_size = config["posts_per_page"]
        write_if_changed(ROOT / "README.md", render_home(config, posts, tils, featured))
        generate_pages(posts, page_size)
        generate_tag_indexes(internal_posts, tils, page_size)
    except (BuildError, KeyError, OSError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
